# Site
repository: pk8498/pk8498.github.io
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: 박혜영
title: Data & Backend Engineer
email: hyeyoung8498@gmail.com

darkmode: false

# Social links
github_username:  pk8498
linkedin_username: hyeyoung-park-a787731b3

# Additional icon links
additional_links:
  - title: Brunch
    icon: fab fa-blogger-b
    url: https://brunch.co.kr/@pk8498


about_profile_image: images/profile.jpeg
about_content: | 
  **서버 백엔드** 및 **데이터 엔지니어링**에 관심이 많은 8년차 개발자입니다. <br/>
  스타트업에서 백엔드 엔지니어로 시작해 플랫폼의 AWS 기반 시스템 구축부터 API 개발 데이터 수집/제공까지 여러부분을 경험할 수 있었습니다. <br/>
  데이터엔지니어로 들어온 서비스 데이터를 수집할 수 있는 환경을 구축하고 가공한 데이터를 분석/마케팅에 활용할 수 있도록 제공하는 부분을 경험했습니다. <br/>
  개인적으로 프로덕션 환경에서 유지보수 하기 좋은 코드를 고민하는 것을 좋아합니다. 회사 업무를 통해 성취감을 얻어내는 활동을 좋아합니다. <br/>
  문서쓰는걸 좋아하고, 업무를 투명하게 공유하는것을 좋아합니다. <br />
  <mark>조직과 팀의 성장</mark>에 대한 많은 고민들을 좋아합니다. <br/>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: TVING
        sub_title: 데이터 엔지니어
        caption: 2021.04.01 ~ 2023.05.31
        link: https://www.tving.com/
        quote: >
          국내 종합엔터테인먼트 OTT 플랫폼
        description: |
          * 데이터 플랫폼 신규 구축 (AWS 기반 환경) / 운영 유지보수
          * 데이터 플랫폼 데이터 입수 전체 아키텍처 설계
          * 데이터 플랫폼 전체 모니터링 시스템 설계 / 구축
          * 데이터웨어하우스 마트 분석환경 개선 및 서버 운영 유지보수
          * 데이터웨어하우스 마트 배치 개발 및 중간 테이블 설계 (시청 기반 정산 데이터 지원 및 내부 분석 마트 지원)
          * 데이터 분석 조직 및 마케팅 파트 지원
          * 팀 내부 추천 시스템 및 검색 시스템 인프라 지원
          * 팀 내 플랫폼 엔지니어링 파트 프로젝트 오너 및 플래닝
          * 테스트 코드 및 코드 규격 정리 및 내부 업무 프로세스/문서화 규격 정리
      - layout: left
        title: Anypoint Media
        sub_title: 백엔드 엔지니어 (광고플랫폼개발팀 - 대리)
        caption: 2016.09 ~ 2020.08
        link: https://anypointmedia.com/
        quote: >
          국내 및 동남아 지역에 스마트 TV용 솔루션 및 서비스를 제공하는 Ad-Tech 기업
        description: |
          * AWS 기반 광고 플랫폼 구축 DevOps 
          * 광고 플랫폼 디바이스 광고 배정, 타겟팅 유지보수 및 개발
          * IDC 내 SKB 유무선 통합형 광고 플랫폼 (SK ONE AD, Oksusu) 개발 및 유지보수 (hadoop 기반 노출 적재, 모니터링 시스템 및 API 개발)
          * 광고 플랫폼 셋톱박스 Push 시스템 인프라 구축 및 운영
          * 광고 플랫폼 집계 시스템 고도화 및 신규 구축
          * 광고 플랫폼 사내 BI 시스템 구축 및 운영
          * 내부 사업부 및 외부 고객사에 광고 지표 추출
      - layout: left
        title: EPOZEN
        sub_title: 백엔드 엔지니어 (인프라 기술개발팀)
        caption: 2015.11 ~ 2016.08
        link: http://www.epozen.com/
        quote: >
          제조업체 솔루션 개발
        description: |
          * 서버 리소스 모니터링 시스템 화면 개발
          * MES Simulation 시스템 개발
          * 사내 인턴 교육 진행
  - title: Projects
    layout: list
    content:
      - layout: left
        title: 데이터웨어하우스 플랫폼 신규 구축
        sub_title: TVING
        caption: 2021.08 ~ 2022.04
        quote: >
          데이터웨어하우스 플랫폼 클라우드(AWS) 활용 신규 구축.
          데이터 수집, 파이프라인 설계, 개발, 배포 및 장애복구 등 전반적 설계와 구축 참여.
        description: |
          * 회사 내 처음으로 데이터웨어하우스 전체 시스템을 설계 및 구축
          * Kubernetes를 활용한 인프라 관리 도입 및 ArgoCD를 통한 배포 자동화 
          * AWS MSK(Kafka), Apache NiFi 를 활용한 실시간 시청 수집 파이프라인 구축
          * Apache Airflow 를 활용한 데이터 ETL 워크플로우 관리
          * 데이터 분석가와 협업하여 마트 설계 및 Redshift 내 집계 마트 구축
          * 장애 모니터링 시스템 구축 및 체계화  
          * Tech Stack : <mark>Kubernetes</mark> <mark>ArgoCD</mark> <mark>MSK</mark> <mark>NiFi</mark> <mark>Airflow</mark> <mark>Java</mark> <mark>Python</mark> <mark>Redshift</mark>
      - layout: left
        title: 데이터 분석 환경 고도화
        sub_title: TVING
        caption: 2022.04 ~ 2022.09
        quote: >
          레거시 데이터 분석 환경 고도화 및 신규 구축
        description: |
          * 기존에 자체적으로 사용하던 BI 시스템 대시보드 및 시스템 Tableau로 전체 이관
          * Apache Zeppelin 구축 및 원천 데이터 활용 분석가 지원
          * IDC 내 레거시 데이터 파이프라인(oracle procedure) AWS 시스템으로 이관 및 고도화
          * 데이터 요구사항에 맞춘 신규 테이블 모델링, 정산 데이터 워크플로우 지원
          * DataHub 신규 구축을 통해 거버넌스를 위한 Data Discovery 기능 지원
          * Tech Stack : <mark>Python</mark> <mark>Zeppelin</mark> <mark>DataHub</mark> <mark>Airflow</mark> <mark>Redshift</mark>
      - layout: left
        title: 데이터 플랫폼 전체 시스템 운영 및 타부서 지원 업무
        sub_title: TVING
        caption: 2022 ~ 2023.05
        quote: >
          신규 구축한 데이터웨어하우스 플랫폼 전체 시스템 운영 및 타 파트(추천,검색,분석가,마케팅 등) 지원 업무
        description: |
          * 기존 시스템 장애 대응 및 유지보수
          * Braze 내 Custom Attribute 정제 데이터 인입을 통한 마케팅 부서 지원
          * 팀 내 추천, 검색 파트에 필요한 데이터 입수 및 집계 마트 구축 지원
          * 팀 내 사이언티스트가 추천 시스템 Airflow 워크플로우를 활용해 트레이닝 할 수 있도록 배포 지원
          * 데이터 분석가들이 활용할 수 있도록 원천 및 중간 집계 마트 구축 및 지원, 마트 스케줄 배포 지원
          * 마케팅 부서 내 데이터 조회 및 활용할 수 있도록 지원 (내부 운영용 웹페이지 개발, 마트 구축 등)
          * 타 부서에서 필요한 원천 메타 데이터 집계 지원
          * 타 부서 시스템 변경으로 인한 기존 시스템 구조 변경 유지보수 지원
          * Tech Stack : <mark>Python</mark> <mark>Zeppelin</mark> <mark>DataHub</mark> <mark>Airflow</mark> <mark>Redshift</mark>
      - layout: left
        title: 광고 플랫폼 집계 시스템 고도화 및 신규 구축
        sub_title: Anypoint Media
#        caption: 2015.11 ~ 2016.08
#        link: http://www.epozen.com/
        quote: >
          사내 빅데이터(TV 광고에 대한 노출 및 채널 데이터)를 이용한 집계 2.0 시스템을 구축.
          ETL 시스템 선정 및 데이터 파이프라인 설계, 개발, 배포 및 장애복구 및 모니터링 시스템까지 전반적으
          로 참여. 구축 후 시스템 운영 및 장애 대응 경험 보유
        description: |
          * Apache NiFi 를 이용한 데이터 파이프라인 구축
          * AWS Glue 및 Crawler 이용한 배치 Workflow 구축
          * Airbnb Druid 기반의 분석 시스템 구축하여 데이터 조회 성능 향상으로 좀 더 나은 사용자 경험 도출
          * AWS Lambda를 이용한 서버리스 시스템 모듈 개발 및 구축
          * AWS Athena 를 활용한 데이터 분석 시스템 구축
          * 데이터 마이그레이션 및 분석을 통해 기존에 존재하지 않았던 광고 도달 지표(Reach1,2,3) 도출 경험
          * Kotlin 을 사용한 Spring Boot 기반의 REST API 개발
          * Tech Stack : <mark>NiFi</mark> <mark>Druid</mark> <mark>AWS Glue</mark> <mark>AWS Lambda</mark> <mark>Serverless</mark> <mark>Kotlin</mark> <mark>Spring Boot</mark> <mark>Rabbit MQ</mark>
      - layout: left
        title: 광고 플랫폼 사내 BI 시스템 구축 및 운영
        sub_title: Anypoint Media
        quote: >
          사내 빅데이터를 시각화 하고, 인사이트를 얻어내기 위해 BI(Business Intelligence) 플랫폼을 설계 및
          구축하여 사내 사업 부서 및 외부에 다양한 리포트 및 대시보드를 제공
        description: |
          * BI 시스템 조사 및 오픈소스인 Redash를 적극적으로 도입하여 사내 시스템에 맞게 커스터마이징하여 구축
          * 사내에서 사용하고 있는 여러 데이터소스들을 한번에 시각화 할 수 있도록 통합
          * 사업부와 협업하여 데이터 시각화 대시보드 설계
          * 사내 개발자 및 사업부의 요구사항 수렴하여 Redash와 Zeppelin을 통한 데이터 추출 업무 진행
          * 사내에서 활발히 사용할 수 있도록 규칙 정의 및 시스템 가이드 배포
          * Tech Stack : <mark>Redash</mark> <mark>Zeppelin</mark> <mark>AWS EMR</mark> <mark>AWS Glue</mark> <mark>Presto</mark>
      - layout: left
        title: SK Broadband, LG U+ 셋톱박스 광고 플랫폼 유지보수 및 광고 배정 기능 개발
        sub_title: Anypoint Media
        quote: >
          셋톱박스 내에 들어가는 광고 에이전트 유지보수 및 개발 작업
        description: |
          * C언어로 구현되어 있는 레거시 셋톱박스 에이전트 유지보수 경험
          * Android(java) 셋톱박스 유지보수 및 추가 개발 경험
          * 개발 후 각 통신사별 셋톱박스로 직접 테스트 진행 경험
          * Tech Stack : <mark>C</mark> <mark>Android</mark> <mark>Java</mark> <mark>Android ADB</mark>
      - layout: left
        title: SKB 유무선 통합형 광고 플랫폼 (SK ONE AD) 개발 및 유지보수
        sub_title: Anypoint Media
        quote: >
          SK BTV, 모바일 앱(oksusu, Btv Plus), 다윈 등 다양한 매체와 네트워크를 대상으로 동영상 광고를
          운영하고 노출 실적을 조회 분석할 수 있는 통합형 광고 플랫폼 구축 프로젝트에 백엔드 개발 참여 및 유지보수
        description: |
          * Grafana, Prometheus, Graphite를 이용한 모니터링 시스템 프레임워크 조사 및 구축
          * Spring Cloud Netflix를 이용한 Microservice 기반 유무선 통합형 광고 플랫폼 배정 API 개발
          * Hadoop Ecosystem 기반 ETL
            * 광고의 노출 로그를 기반으로 변형, 적재 및 분석
            * Spring XD 배치 스트림 개발 경험 (광고 로그 기반 데이터 변형 위주의 스트림 개발)
          * IMDG 기반의 분산 캐시 서버 구축 경험
            * hazelcast를 이용한 분산 캐시 시스템 구축
          * Apache Mesos 및 Marathon을 이용하여 Microservice 도커 컨테이너 오케스트레이션 구축, 운영
          * SK Broadband 요구사항 수렴하여 Zeppelin을 통한 데이터 추출 업무 진행
          * Tech Stack : <mark>Spring Boot</mark> <mark>Java</mark> <mark>Hazelcast</mark> <mark>Ambari</mark> <mark>Hadoop</mark> <mark>Mesos, Marathon</mark> <mark>Grafana</mark> <mark>Prometheus</mark> <mark>Graphite</mark> <mark>Oracle</mark>
      - layout: left
        title: 광고 플랫폼 디바이스 광고 배정, 타겟팅 유지 보수 및 개발
        sub_title: Anypoint Media
        quote: >
          SKB, UPLUS 실시간 TV 광고 플랫폼 유지 보수 및 광고 배정, 타겟팅에 대한 백엔드 API 개발 및 운영
        description: |
          * Java 를 사용한 Spring Boot 기반의 REST API 개발 및 유지보수
          * Tech Stack : <mark>Spring Boot</mark> <mark>Java</mark> <mark>Gradle</mark>
      - layout: left
        title: 광고 플랫폼 셋톱박스 Push 시스템 구축 및 운영
        sub_title: Anypoint Media
        quote: >
          광고가 셋톱박스에 실질적으로 나갈 수 있게 해주는 Push 시스템을 구축, 인프라 관리 등 운영 참여
        description: |
          * AWS, NCloud, CloudZ 클라우드 환경에서의 시스템 및 운영 경험 보유
          * 서버에 수백만의 커넥션이 유지될 수 있도록 Mesos, Marathon을 이용한 오토 스케일링 환경 구축 및 Linux 서버 튜닝 경험
          * Tech Stack : <mark>Spring Boot</mark> <mark>Java</mark> <mark>Gradle</mark> <mark>Netty</mark> <mark>AWS</mark> <mark>NCloud</mark> <mark>CloudZ</mark>
      - layout: left
        title: 외 DevOps 업무 경험
        sub_title: Anypoint Media
        quote: >
          사내 CI/CD 등 인프라 구축 및 관리,
          사내 드라이브 관리 및 협업을 위한 메뉴얼 사이트 정리, 배포.
          사내 세그먼트 관리 사이트 유지보수 및 기능 추가 등 (vue, 간단 spark ml 활용 등)
      - layout: left
        title: 서버 리소스 모니터링 시스템 개발
        sub_title: EPOZEN
        quote: >
          SK Hynix 등 여러 외부업체의 서버 중 사내에서 관리하는 서버의 리소스 모니터링 시스템 화면 설계 및 개발
        description: |
          * Vaadin을 이용한 사내 서버 리소스 모니터링 대시보드 프론트 개발 경험
          * Vaadin 프레임워크 선정 참여 및 해당 프레임워크에 대한 가이드 생성하여 배포
          * 프레임워크 사용 방䢲 및 코드 정리하여 SI 팀에서 사용할 수 있도록 배포
          * Tech Stack : <mark>Vaddin</mark> <mark>Java</mark> <mark>Maven</mark>
      - layout: left
        title: MES Simulation 시스템 개발
        sub_title: EPOZEN
        quote: >
          사내 솔루션 중 하나인 SK Hynix의 반도체 MES에 대한 시뮬레이션 시스템의 프론트 및 백엔드 개발 참여
        description: |
          * Java를 사용한 Spring MVC 기반의 REST API 개발
          * C# 을 이용한 UI 개발
          * Tech Stack : <mark>Spring MVC</mark> <mark>Java</mark> <mark>C#</mark>
      - layout: left
        title: 외 업무 경험
        sub_title: EPOZEN
        quote: >
          기타 사내 인턴 교육 진행 등
  - title: Education
    layout: list
    content:
      - layout: left
        title: 인하공업전문대학
        sub_title: 컴퓨터시스템
        caption: 2013.03 ~ 2016.02
        description: | 
          (4.25/4.5)
      - layout: left
        title: 숭실평생원격교육원
        sub_title: 컴퓨터공학사인증
        caption: 2017.02
        description: | 
          (4.25/4.5)
  - title: A Little More About Me
    layout: text
    content: | 
      * [AWS Industry Week 2021 발표](https://kr-resources.awscloud.com/aws-industry-week-2021/media-track-session2)
      * TVING DEV DAY 발표 2022 (출처: 티빙블로그)<br/><img src="images/devday2022.png" style="width:50%">

footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
